
// global
export const GET_PAGE_MODEL = 'GET_PAGE_MODEL'
export const INIT_LAYOUT = 'INIT_LAYOUT'
export const TOGGLE_AUTHORING = 'TOGGLE_AUTHORING'

// component menu
export const SET_MENU_POSITION = 'SET_MENU_POSITION'
export const SET_MENU_DIFF = 'SET_MENU_DIFF'
export const TOGGLE_DRAG_CANVAS = 'TOGGLE_DRAG_CANVAS'

// component settings
export const TOGGLE_COMPONENT_SETTINGS = 'TOGGLE_COMPONENT_SETTINGS'
export const OPEN_COMPONENT_SETTINGS = 'OPEN_COMPONENT_SETTINGS'
export const CLOSE_COMPONENT_SETTINGS = 'CLOSE_COMPONENT_SETTINGS'
export const EDIT_COMPONENT_SETTINGS = 'EDIT_COMPONENT_SETTINGS'
export const CLEAR_COMPONENT_SETTINGS = 'CLEAR_COMPONENT_SETTINGS'

// add/edit/update/delete
export const ADD_COMPONENT = 'ADD_COMPONENT'
export const EDIT_COMPONENT = 'EDIT_COMPONENT'
export const UPDATE_COMPONENT = 'UPDATE_COMPONENT'
export const DELETE_COMPONENT = 'DELETE_COMPONENT'